version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: hoge
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build: .
    environment:
      MYAPP_DATABASE_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db

volumes:
  db-data:
